#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/kubernetes/examples/web.pod
    owner: "root:root"
    permissions: "0644"
    content: |
      kind: Pod
      apiVersion: v1beta1
      id: web
      labels:
        name: web
      desiredState:
        manifest:
          version: v1beta1
          id: web
          containers:
            - name: web
              image: larsks/thttpd
              ports:
                - containerPort: 80
  - path: /etc/kubernetes/examples/web.service
    owner: "root:root"
    permissions: "0644"
    content: |
      kind: Service
      apiVersion: v1beta1
      id: web
      port: 8000
      selector:
        name: web
      containerPort: 80
  - path: /etc/kubernetes/examples/stress.replica
    owner: "root:root"
    permissions: "0644"
    content: |
      apiVersion: v1beta3
      kind: ReplicationController
      id: stress
      metadata:
        name: stress-controller
      spec:
        replicas: 1
        # selector identifies the set of Pods that this
        # replicaController is responsible for managing
        selector:
          name: stress
        # podTemplate defines the 'cookie cutter' used for creating
        # new pods when necessary
        template:
          metadata:
            labels:
              # Important: these labels need to match the selector above
              # The api server enforces this constraint.
              name: stress
          spec:
            containers:
              - name: stress
                image: larsks/stress
                command: ["--cpu", "1"]
